version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=mysecretkey
    depends_on:
      - mongo
      - redis
    networks:
      - app_network

  product-service:
    build: ./product-service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/productdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    networks:
      - app_network

 
  mongo:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:6.2
    container_name: redis_db
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
