version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: "mongodb://mongodb:27017/product-db"
      REDIS_URL: "redis://redis:6379"

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: "mongodb://mongodb:27017/user-db"
      REDIS_URL: "redis://redis:6379"

  krakend:
    image: devopsfaith/krakend:latest
    container_name: krakend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json
    depends_on:
      - product-service
      - user-service
    command: [ "run", "-dc", "/etc/krakend/krakend.json" ]

volumes:
  mongo_data:
